name: home-assistant

services:
  home-assistant:
    cap_add:
      - NET_ADMIN
      - NET_RAW
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable@sha256:6340a3de3917a9b19368e767310a96dd090f6a19aca8aeadf87fd1145cec9682
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro

volumes:
  home-assistant:
    external: true
    name: home-assistant
