name: home-assistant

services:
  home-assistant:
    cap_add:
      - NET_ADMIN
      - NET_RAW
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable@sha256:ae0800c81fea16bc1241ce03bddb9c6260566e90f58b09d3e5a629e4f68bdc0b
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro

volumes:
  home-assistant:
    external: true
    name: home-assistant
