configs:
  glance.yml:
    file: ./glance.yml

name: glance

services:
  glance:
    configs:
      - source: glance.yml
        target: /app/config/glance.yml
    container_name: glance
    env_file:
      - secrets.enc.env
    image: glanceapp/glance:latest@sha256:9dfb09470b207dcb67ac715994bdb1929374ba3f9c0d7df7462c24adf10fd073
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
