configs:
  glance.yml:
    file: ./glance.yml

name: glance

services:
  glance:
    configs:
      - source: glance.yml
        target: /app/config/glance.yml
    container_name: glance
    env_file:
      - secrets.enc.env
    image: glanceapp/glance:latest@sha256:32ab73d80f2b8b5fb0735b0431deb36b93fbb6b2fb43592449b0178c8b83e350
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
